app/models/Reserva.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "reserva".
 *
 * @property int $id
 * @property int $paciente_id
 * @property string $fecha
 * @property string $hora
 * @property string $hora_ingreso
 * @property string $hora_llegada
 * @property string $tipo
 * @property int $num_ficha
 * @property int $tratamiento_id
 * @property int $num_ficha
 * @property string $observacion
 *
 * @property TipoTratamiento $tratamiento
 * @property Paciente $paciente
 */
class Reserva extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'reserva';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['fecha', 'hora', 'tipo', 'hora'], 'required'],
            [['paciente_id', 'tratamiento_id','num_ficha'], 'integer'],
            [['fecha', 'hora', 'hora_ingreso', 'hora_llegada'], 'safe'],
            [['tipo','observacion'], 'string'],
            [['tratamiento_id'], 'exist', 'skipOnError' => true, 'targetClass' => TipoTratamiento::className(), 'targetAttribute' => ['tratamiento_id' => 'id']],
            [['paciente_id'], 'exist', 'skipOnError' => true, 'targetClass' => Paciente::className(), 'targetAttribute' => ['paciente_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'paciente_id' => 'Paciente',
            'fecha' => 'Fecha',
            'hora' => 'Hora',
            'hora_ingreso' => 'Hora Ingreso',
            'hora_llegada' => 'Hora Llegada',
            'tipo' => 'Tipo',
            'num_ficha' => 'Número ficha',
            'tratamiento_id' => 'Tratamiento',
            'num_ficha' => 'Número Ficha',
            'observacion' => 'Observación'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTratamiento()
    {
        return $this->hasOne(TipoTratamiento::className(), ['id' => 'tratamiento_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaciente()
    {
        return $this->hasOne(Paciente::className(), ['id' => 'paciente_id']);
    }
}

app/controllers/ReservaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Kardex;
use app\models\Reserva;
use yii\web\Controller;
use app\models\Paciente;
use yii\filters\VerbFilter;
use app\models\ReservaSearch;
use app\components\PFunciones;
use yii\web\NotFoundHttpException;

/**
 * ReservaController implements the CRUD actions for Reserva model.
 */
class ReservaController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Reserva models.
     * @return mixed
     */
    public function actionIndex()
    {
        PFunciones::edad(Paciente::find()->all());

        $searchModel = new ReservaSearch();
        $searchModel->fecha = date('d-m-Y');
        // $searchModel->num_ficha = 0;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,false);

        $dataProvider->setSort([
            'defaultOrder' => ['hora' => SORT_ASC],
        ]);

        $dataProvider2 = $searchModel->search(Yii::$app->request->queryParams,true);

        $dataProvider2->setSort([
            'defaultOrder' => ['num_ficha' => SORT_ASC],
        ]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'dataProvider2' => $dataProvider2,
        ]);
    }

    /**
     * Displays a single Reserva model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Reserva model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($tipo,$paciente_id = null)
    {
        $model = new Reserva();
        $model->paciente_id = $paciente_id;
        $model->fecha = date('d-m-Y');
        $request = Yii::$app->request;
        if ($model->load($request->post())) {
            
            //$maxficha = Reserva::find()->where(['fecha'=> $request->post('Reserva')['fecha']])->max('num_ficha');
            $hora = Reserva::find()->where(['hora'=>$request->post('Reserva')['hora'],'fecha'=>$request->post('Reserva')['fecha']])->exists();
            $paciente = Reserva::find()->where(['paciente_id' => $request->post('Reserva')['paciente_id'], 'fecha' => $request->post('Reserva')['fecha']])->exists();
            if($hora || $paciente){
                Yii::$app->session->setFlash('error', 'Ya se encuentra el usuario y/o horario asignado');
                return $this->redirect(['create','tipo'=>$tipo]);
            }

            $model->num_ficha = 0;
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'tipo' => $tipo
        ]);
    }

    /**
     * Updates an existing Reserva model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($tipo,$id, $paciente_id = null)
    {
        $model = $this->findModel($id);
        // $tipo = 'reserva';
        $model->paciente_id = $paciente_id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'tipo' => $tipo,
        ]);
    }

    public function actionFicha($id)
    {

        $pacc = Reserva::find()->where(['fecha' => date('d-m-Y'), 'id' => $id])->one();
        if ($pacc->num_ficha > 0) {
            Yii::$app->session->setFlash('error', 'El paciente ya tiene una ficha asignada');
            return $this->redirect(['index']);
        }
        // $model = new Reserva();
        // $pacientes = Reserva::find()->where(['fecha' => date('Y-m-d')])->andWhere(['!=', 'paciente_id', $id])->andWhere(['>=', 'num_ficha', 1])->all();
        // $paciente = Reserva::find()->where(['paciente_id' => $id, 'fecha' => date('Y-m.d')])->one();
        $pacienteultimaficha = Reserva::find()->where(['fecha' => date('d-m-Y')])->andWhere(['!=', 'id', $id])->andWhere(['>=', 'num_ficha', 1])->orderBy(["num_ficha"=> SORT_DESC])->one();
        // $pacc = Reserva::find()->where(['id' => $id])->one();
        if ($pacienteultimaficha) {
            $pacc->num_ficha = $pacienteultimaficha->num_ficha+1;
        }else{
            $pacc->num_ficha = 1;
        }
        $pacc->save();
        return $this->redirect(['index']);
        // return $this->render('ficha', [
        //     'model' => $model,
        //     'paciente' => $paciente,
        //     'pacientes' => $pacientes,
        // ]);




        // $existe = Reserva::find()->where(['fecha' => date('Y-m-d'), 'paciente_id' => $id])->one();
        // if ($existe->num_ficha == NULL) {
        //     Yii::$app->session->setFlash('error', 'El paciente no tiene un numero de ficha asignado');
        //     return $this->redirect(['index']);
        // }
        // $model = new Reserva();
        // $pacientes = Reserva::find()->where(['fecha' => date('Y-m-d')])->andWhere(['!=', 'paciente_id', $id])->andWhere(['>=', 'num_ficha', 1])->all();
        // $paciente = Reserva::find()->where(['paciente_id' => $id, 'fecha' => date('Y-m.d')])->one();

        // $request = Yii::$app->request;
        // if ($request->isPost) {
        //     $paca = Reserva::find()->where(['paciente_id' => $id, 'fecha' => date('Y-m-d')])->one();
        //     $pacc = Reserva::find()->where(['paciente_id' => $request->post('Reserva')['paciente_id'], 'fecha' => date('Y-m.d')])->one();
        //     //ficha paciente actual
        //     $fichapaca = $paca->num_ficha;
        //     //ficha paciente seleccioando
        //     $fichapacc = $pacc->num_ficha;

        //     //cambio de ficha al paciente elegido
        //     $pacc->num_ficha = $fichapaca;
        //     //cambio de ficha al paciente actual
        //     $paca->num_ficha = $fichapacc;

        //     //guardamos las fichas cambiadas
        //     $pacc->save();
        //     $paca->save();

        //     return $this->redirect(['index']);
        // }

        // return $this->render('ficha', [
        //     'model' => $model,
        //     'paciente' => $paciente,
        //     'pacientes' => $pacientes,
        // ]);
    }

    public function actionFicharemove($id)
    {
        $pacc = Reserva::find()->where(['fecha' => date('d-m-Y'), 'id' => $id])->one();
        $pacc->num_ficha = 0;
        $pacc->save();
        return $this->redirect(['index']);
    }

    public function actionNumficha($id)
    {
        $reserva = Reserva::find()->where(['paciente_id' => $id, 'fecha' => date('d-m-Y')])->one();
        $reservacount = Reserva::find()->where(['paciente_id' => $id, 'fecha' => date('d-m-Y')])->count();

        if ($reservacount > 0) {
            echo "<option value='" . $reserva->num_ficha . "'>" . $reserva->num_ficha . "</option>";
        } else {
            echo "<option value='0'></option>";
        }
    }

    /**
     * Deletes an existing Reserva model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        // PFunciones::ficha(Reserva::find()->where(['fecha' => date('Y-m-d')])->all());
        return $this->redirect(['index']);
    }

    /**
     * Finds the Reserva model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Reserva the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Reserva::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

app/views/reserva/_form.php
<?php

use yii\helpers\Html;
use app\models\Paciente;
use app\models\TipoTratamiento;
use kartik\date\DatePicker;
use kartik\form\ActiveForm;
use kartik\select2\Select2;
use kartik\time\TimePicker;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Reserva */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reserva-form">
    <?php $form = ActiveForm::begin(); ?>
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
                <div class="form-group">
                    <?= $form->field($model, 'paciente_id')->widget(Select2::classname(), [
                            'data' => ArrayHelper::map(Paciente::find()->all(), 'id', 'nombrecompleto'),
                            'options' => ['placeholder' => 'Seleccione un paciente...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ],
                        ]);
                    ?>                
                </div>
            </div>
            <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12" style="margin-top: 20px;">
                <div class="form-group">
                    <?= Html::a('<i class="glyphicon glyphicon-plus-sign"></i> Nuevo paciente', ['/paciente/create', 'tipo'=>$tipo,'id'=>$model->id], ['class'=>'btn btn-success waves-effect waves-classic'])?>
                </div>
            </div>
        </div>


        <?= $form->field($model, 'fecha')->widget(
            DatePicker::className(),
                [
                    'name' => 'check_issue_date',
                    'value' => date('y-m-d', strtotime('+2 days')),
                    'options' => ['placeholder' => 'Seleccione la fecha ...'],
                    'pluginOptions' => [
                        // 'startDate' => date('y-m-d'),
                        'format' => 'dd-mm-yyyy',
                        'autoclose' => true,
                        // 'todayHighlight' => true
                    ]
                ]
            );
        ?>

        <?= $form->field($model, 'hora')->widget(
            TimePicker::className(),
                [
                    'pluginOptions' => [
                        'showSeconds' => false,
                        'showMeridian' => false,
                        'minuteStep' => 15,
                        // 'secondStep' => 5,
                    ],
                ]
            );
        ?>
        <?php if(!$model->isNewRecord){ ?>
            <?= $form->field($model, 'hora_ingreso')->widget(
                TimePicker::className(),
                    [
                        'pluginOptions' => [
                            'showSeconds' => false,
                            'showMeridian' => false,
                            'minuteStep' => 1,
                            // 'secondStep' => 5,
                        ]
                    ]
                );
            ?>

            <?= $form->field($model, 'hora_llegada')->widget(
                TimePicker::className(),
                    [
                        'pluginOptions' => [
                            'showSeconds' => false,
                            'showMeridian' => false,
                            'minuteStep' => 1,
                            // 'secondStep' => 5,
                        ]
                    ]
                );
            ?>
        <?php } ?>

        <?= $form->field($model, 'tipo')->widget(Select2::classname(), [
                'data' => [
                    'Consulta' => 'Consulta',
                    'Reconsulta' => 'Reconsulta',
                    'Tratamiento' => 'Tratamiento',
                ],
                'options' => ['placeholder' => 'Seleccione una opcion ...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]);
        ?>

        <?= $form->field($model, 'tratamiento_id')->widget(Select2::classname(), [
                'data' => ArrayHelper::map(TipoTratamiento::find()->all(), 'id', 'nombre'),
                'options' => ['placeholder' => 'Seleccione un tratamiento...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]);
        ?>

        <?= $form->field($model, 'observacion')->textInput(['maxlength' => true]) ?>

        <div class="form-group text-right">
            <?= Html::a("<i class='material-icons'>clear</i> " . 'Cerrar', ['index'], [
                'class' => 'btn btn-default',
                'title' => 'Cerrar',
            ]) ?>
            <?= Html::submitButton("<i class='material-icons'>save</i> " . 'Guardar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-warning']) ?>
        </div>
    <?php ActiveForm::end(); ?>
</div>

app/views/reserva/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ReservaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reserva-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?php // echo $form->field($model, 'id') ?>

    <?php // echo $form->field($model, 'paciente_id') ?>

    <?php echo $form->field($model, 'fecha') ?>

    <?php // echo $form->field($model, 'hora') ?>

    <?php // echo $form->field($model, 'consulta') ?>

    <?php // echo $form->field($model, 'reconsulta') ?>

    <?php // echo $form->field($model, 'tratamiento_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/reserva/create.php
+<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Reserva */

$this->title = 'Nueva Reserva';
$this->params['breadcrumbs'][] = ['label' => 'Reservas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reserva-create">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 col-centered">
            <div class="card">
                <div class="card-content">
                    <h4><?= Html::encode($this->title) ?></h4>
                    <?= $this->render('_form', [
                        'model' => $model,
                        'tipo' => $tipo,
                    ]) ?>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/reserva/ficha.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use kartik\date\DatePicker;
use kartik\form\ActiveForm;
use kartik\select2\Select2;
use yii\widgets\DetailView;
use yii\helpers\ArrayHelper;
use app\models\TipoTratamiento;

/* @var $this yii\web\View */
/* @var $model app\models\Reserva */

$this->title = 'Cambio Ficha Paciente: ' . $paciente->paciente->nombrecompleto;
$this->params['breadcrumbs'][] = ['label' => 'Pacientes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);

?>
<div class="paciente-create">
    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 col-centered">
            <div class="card">
                <div class="card-content">
                    <h4><?= Html::encode($this->title) ?></h4>
                    <div class="reserva-form">
                        <?php $form = ActiveForm::begin(); ?>
                            <div class="row">
                                <div class="col-lg-9 col-sm-9 col-md-9 col-xs-12">
                                    <label>Paciente Actual</label>
                                    <input class="form-control" type="text" disabled value="<?= $paciente->paciente->nombrecompleto ?>">
                                </div>
                                <div class="col-lg-3 col-sm-3 col-md-3 col-xs-12">
                                    <label>Número Ficha</label>
                                    <input class="form-control" type="text" disabled value="<?= $paciente->num_ficha ?>">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-9 col-sm-9 col-md-9 col-xs-12">
                                    <?= $form->field($model, 'paciente_id')->widget(Select2::classname(), [
                                        'data' => ArrayHelper::map($pacientes, 'paciente.id',
                                            function ($model) {
                                                return $model->paciente->nombrecompleto .' - Ficha '. $model['num_ficha'].' - '. $model['hora'];
                                            }
                                        ),
                                        'options' => [
                                            'placeholder' => 'Seleccione un paciente...',
                                            'onchange' => '$.post("/reserva/numficha?id=' . '"+$(this).val(),function(data){
                                                $("select#reserva-num_ficha").html(data);
                                            });',
                                        ],
                                        'pluginOptions' => [
                                            'allowClear' => true
                                        ],
                                    ]);
                                    ?>
                                </div>
                                <div class="col-lg-3 col-sm-3 col-md-3 col-xs-12">
                                    <?= $form->field($model, 'num_ficha')->dropDownList(['prompt' => ''], ['disabled' => 'disabled']) ?>
                                </div>
                            </div>
                            <div class="form-group text-right">
                                <a href="<?= Url::to(['/reserva/index']) ?>" class="btn btn-default">
                                    <i class="material-icons">clear</i> Cerrar
                                </a>
                                <button class="btn btn-success" type="submit">
                                    <i class="material-icons">save</i> Cambiar
                                </button>
                            </div>
                        <?php ActiveForm::end(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/reserva/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Reserva */

$this->title = 'Modificar Reserva: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Reservas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Reservas '.$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reserva-update">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 col-centered">
            <div class="card">
                <div class="card-content">
                    <h4><?= Html::encode($this->title) ?></h4>
                    <?= $this->render('_form', [
                        'model' => $model,
                        'tipo' => $tipo,
                    ]) ?>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/reserva/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Reserva */

$this->title = 'Reservas ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Reservas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="reserva-view">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 col-centered">
            <div class="card">
                <div class="card-content">
                    <h4><?= Html::encode($this->title) ?></h4>
                    <hr>

                <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            [
                                'label' => 'Paciente',
                                'attribute' => 'paciente.nombrecompleto'
                            ],
                            [
                                'label' => 'Paciente nuevo',
                                'attribute' => 'observacion'
                            ],
                            'fecha',
                            'hora',
                            'hora_ingreso',
                            'tipo',
                            'num_ficha',
                            [
                                'label' => 'Tratamiento',
                                'attribute' => 'tratamiento.codigo'
                            ]
                        ],
                    ]) ?>

                     <div class="form-group text-right">
                        <?= Html::a( "<i class='material-icons'>clear</i> ".'Cerrar', ['index'], ['class' => 'btn btn-default', 'title'=>'Cerrar',]) ?>
                        <?= Html::a( "<i class='material-icons'>edit</i> ".'Modificar', ['update','id' => $model->id, 'tipo' => 'reserva'], ['class' => 'btn btn-warning', 'title'=>'Modificar',]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>