app/models/BizRule.php
<?php

namespace app\models;

use Yii;
use yii\rbac\Rule;
use mdm\admin\components\Configs;

/**
 * BizRule
 *
 * @author Misbahul D Munir <misbahuldmunir@gmail.com>
 * @since 1.0
 */
class BizRule extends \yii\base\Model
{
    /**
     * @var string name of the rule
     */
    public $name;

    /**
     * @var integer UNIX timestamp representing the rule creation time
     */
    public $createdAt;

    /**
     * @var integer UNIX timestamp representing the rule updating time
     */
    public $updatedAt;

    /**
     * @var string Rule classname.
     */
    public $className;

    /**
     * @var Rule
     */
    private $_item;

    /**
     * Initilaize object
     * @param \yii\rbac\Rule $item
     * @param array $config
     */
    public function __construct($item, $config = [])
    {
        $this->_item = $item;
        if ($item !== null) {
            $this->name = $item->name;
            $this->className = get_class($item);
        }
        parent::__construct($config);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'className'], 'required'],
            [['className'], 'string'],
            [['className'], 'classExists']
        ];
    }

    /**
     * Validate class exists
     */
    public function classExists()
    {
        if (!class_exists($this->className)) {
            $message = Yii::t('rbac-admin', "Unknown class '{class}'", ['class' => $this->className]);
            $this->addError('className', $message);
            return;
        }
        if (!is_subclass_of($this->className, Rule::className())) {
            $message = Yii::t('rbac-admin', "'{class}' must extend from 'yii\rbac\Rule' or its child class", [
                    'class' => $this->className]);
            $this->addError('className', $message);
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('rbac-admin', 'Name'),
            'className' => Yii::t('rbac-admin', 'Class Name'),
        ];
    }

    /**
     * Check if new record.
     * @return boolean
     */
    public function getIsNewRecord()
    {
        return $this->_item === null;
    }

    /**
     * Find model by id
     * @param type $id
     * @return null|static
     */
    public static function find($id)
    {
        $item = Configs::authManager()->getRule($id);
        if ($item !== null) {
            return new static($item);
        }

        return null;
    }

    /**
     * Save model to authManager
     * @return boolean
     */
    public function save()
    {
        if ($this->validate()) {
            $manager = Configs::authManager();
            $class = $this->className;
            if ($this->_item === null) {
                $this->_item = new $class();
                $isNew = true;
            } else {
                $isNew = false;
                $oldName = $this->_item->name;
            }
            $this->_item->name = $this->name;

            if ($isNew) {
                $manager->add($this->_item);
            } else {
                $manager->update($oldName, $this->_item);
            }

            return true;
        } else {
            return false;
        }
    }

    /**
     * Get item
     * @return Item
     */
    public function getItem()
    {
        return $this->_item;
    }
}

app/models/Paciente.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "paciente".
 *
 * @property int $id
 * @property string $nombres
 * @property string $apellidos
 * @property string $fecha_nacimiento
 * @property int $edad
 * @property string $telefono
 * @property string $celular
 * @property string $tipo_paciente
 *
 * @property Emergencia[] $emergencias
 * @property Kardex[] $kardexes
 * @property Reserva[] $reservas
 */
class Paciente extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'paciente';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombres', 'apellidos', 'fecha_nacimiento'], 'required'],
            [['fecha_nacimiento'], 'safe'],
            [['edad'], 'integer'],
            [['tipo_paciente'], 'string'],
            [['nombres', 'apellidos'], 'string', 'max' => 255],
            [['telefono', 'celular'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombres' => 'Nombres',
            'apellidos' => 'Apellidos',
            'fecha_nacimiento' => 'Fecha Nacimiento',
            'edad' => 'Edad',
            'telefono' => 'Telefono',
            'celular' => 'Celular',
            'tipo_paciente' => 'Tipo Paciente',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmergencias()
    {
        return $this->hasMany(Emergencia::className(), ['paciente_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKardexes()
    {
        return $this->hasMany(Kardex::className(), ['paciente_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReservas()
    {
        return $this->hasMany(Reserva::className(), ['paciente_id' => 'id']);
    }

    public function getNombrecompleto()
    {
        return $this->nombres . ' ' . $this->apellidos;
    }

    public function getKardex()
    {
        $kardex = $this->getKardexes()->one();
        if ($kardex) {
            return $kardex;
        }
        return null;
    }
}

app/controllers/PacienteController.php
<?php

namespace app\controllers;

use Yii;
use kartik\mpdf\Pdf;
use app\models\Pagos;
use app\models\Kardex;
use app\models\Receta;
use app\models\Reserva;
use yii\web\Controller;
use app\models\Paciente;
use app\models\PagoDetalle;
use app\models\PagosSearch;
use yii\filters\VerbFilter;
use app\models\PagoConsulta;
use app\models\RecetaSearch;
use app\models\RecetaSearch1;
use app\models\DetalleReceta;
use app\components\PFunciones;
use app\models\PacienteSearch;
use app\models\TipoTratamiento;
use app\models\PagoConsultaSearch;
use yii\web\NotFoundHttpException;

/**
 * PacienteController implements the CRUD actions for Paciente model.
 */
class PacienteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Paciente models.
     * @return mixed
     */
    public function actionIndex()
    {
        PFunciones::edad(Paciente::find()->all());

        $searchModel = new PacienteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Paciente model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Paciente model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Paciente();
        $tipo = Yii::$app->request->get('tipo');
        $id = Yii::$app->request->get('id');
        $request = Yii::$app->request;

        if ($model->load(Yii::$app->request->post())) {
            $exist = Paciente::find()->where(['nombres' => $request->post('Paciente')['nombres'], 'apellidos' => $request->post('Paciente')['apellidos']])->exists();
            if ($exist) {
                throw new \Exception('El paciente ya se registro en el sistema');
            }
            $model->edad = date("Y") - date("Y", strtotime($request->post('Paciente')['fecha_nacimiento']));
            $model->save();
            $tipo = $request->get('tipo');
            $id = Yii::$app->request->get('id');
            if ($tipo && !$id) {
                return $this->redirect([$tipo . '/create', 'tipo' => $tipo, 'paciente_id' => $model->id]);
            } elseif ($tipo && $id) {
                return $this->redirect([$tipo . '/update', 'tipo' => $tipo, 'paciente_id' => $model->id, 'id' => $id]);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'tipo' => $tipo,
            'id' => $id,
        ]);
    }

    /**
     * Updates an existing Paciente model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $tipo = '';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'tipo' => $tipo,
        ]);
    }

    /**
     * Deletes an existing Paciente model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        //////verificacion si ya esta asignado el paciente a un kardex y una reserva
        $kardex = Kardex::find()->where(['paciente_id' => $id])->one();
        if ($kardex) {
            Yii::$app->session->setFlash('error', 'No se pudo eliminar, el paciente ya esta asiganda a una reserva y/o kardex');
            return $this->redirect(['index']);
        }

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionKardex($id)
    {
        $paciente = $this->findModel($id);
        $model = new Kardex();
        $kardexes = kardex::find()->where(['paciente_id' => $id])->all();
        // print_r($kardexes[2]->getPagostoal());
        // echo "aaaa";
        // print_r($kardexes);
        $request = Yii::$app->request;
        $model->fecha = date('Y-m-d');
        $tipo = Yii::$app->request->get('tipo');

        if ($model->load($request->post())) {
            // $maxficha = Reserva::find()->where(['fecha' => $request->post('Kardex')['fecha']])->max('num_ficha');

            ///tipo = paciente(crear reserva - item kardex)
            if ($tipo == 'paciente') {
                if (Yii::$app->user->can('Secretaria') || Yii::$app->user->can('Administrador')) {
                    //registro del kardex
                    $reserva = new Reserva;
                    $reserva->fecha = date('d-m-Y');
                    $reserva->paciente_id = $paciente->id;
                    // $reserva->fecha = $request->post('Kardex')['fecha'];
                    $reserva->hora = date("h:i:s");
                    $reserva->hora_ingreso = date("h:i:s");
                    $reserva->tipo = $request->post('Kardex')['tipo'];
                    $reserva->num_ficha = 0;
                    $reserva->tratamiento_id = $request->post('Kardex')['tratamiento_id'];
                    $reserva->save();
                    $model->paciente_id = $id;
                    $model->estado = 'Activo';
                    $model->save();
                    // return $this->redirect(['kardex', 'id' => $model->paciente_id]);
                    $this->redirect(Yii::$app->request->referrer);
                }
                if (Yii::$app->user->can('Doctor')) {
                    //creacion de la reserva
                    $reserva = new Reserva;
                    $reserva->fecha = date('d-m-Y');

                    $reserva->paciente_id = $paciente->id;
                    // $reserva->fecha = $request->post('Kardex')['fecha'];
                    $reserva->hora = date("h:i:s");
                    $reserva->hora_ingreso = date("h:i:s");
                    $reserva->tipo = $request->post('Kardex')['tipo'];
                    $reserva->num_ficha = 0;
                    $reserva->tratamiento_id = $request->post('Kardex')['tratamiento_id'];
                    $reserva->save();

                    //registro del kardex
                    $model->paciente_id = $id;
                    $model->estado = 'Pendiente';
                    $model->save();
                    // return $this->redirect(['kardex', 'id' => $model->paciente_id]);
                    $this->redirect(Yii::$app->request->referrer);
                }
            } else {
                ///tipo = reserva (crear item kardex)
                // if($tipo == 'reserva'){
                if (Yii::$app->user->can('Secretaria') || Yii::$app->user->can('Administrador')) {
                    //registro del kardex
                    $model->paciente_id = $id;
                    $model->estado = 'Activo';
                    $model->save();
                    // return $this->redirect(['kardex', 'id' => $model->paciente_id]);
                    $this->redirect(Yii::$app->request->referrer);
                }
                if (Yii::$app->user->can('Doctor')) {
                    //registro del kardex
                    $model->paciente_id = $id;
                    $model->estado = 'Pendiente';
                    $model->save();
                    // return $this->redirect(['kardex', 'id' => $model->paciente_id]);
                    $this->redirect(Yii::$app->request->referrer);
                }
            }
        }

        return $this->render('kardex', [
            'paciente' => $paciente,
            'kardexes' => $kardexes,
            'model' => $model,
        ]);
    }

    public function actionKardexdelete($id)
    {
        // print_r("entre a Consulta");

        $model = Kardex::findOne($id);

        $pago = Pagos::find()->where(['kardex_id' => $id])->one();
        $pagoConsulta = PagoConsulta::find()->where(['kardex_id' => $id])->one();
        if ($model['tipo'] === "Tratamiento") {
            // print_r("entre a trata");
            if ($pago) {
                Yii::$app->session->setFlash('error', "El kardex tiene pagos asignados");
                return $this->redirect(Yii::$app->request->referrer);
            }else{
            }

        } else {
            if ($pagoConsulta) {
                Yii::$app->session->setFlash('error', "El kardex tiene pagos asignados");
                return $this->redirect(Yii::$app->request->referrer);
            }
        }

        // $pagoConsulta = PagoConsulta::find()->where(['kardex_id'=>$id])->one();
        // if ($model['tipo'] === "Tratamiento") {
        //     print_r("entre a trata");

        // if(!$pago){
        //     Yii::$app->session->setFlash('error', "El kardex tiene pagos asignados");
        //     return $this->redirect(Yii::$app->request->referrer);

        // }

        // if(PFunciones::pageTotal($pago->pagodetalles,'monto_pago') < $pago->monto_total || PFunciones::pageTotal($pago->pagodetalles, 'cantidad') < $pago->cantidad_jeringas){

app/views/paciente/_form.php
<?php

use yii\helpers\Html;
use kartik\file\FileInput;
use kartik\date\DatePicker;
use kartik\form\ActiveForm;
use kartik\select2\Select2;
use kartik\switchinput\SwitchInput;

/* @var $this yii\web\View */
/* @var $model app\models\Paciente */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="paciente-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombres')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'apellidos')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'fecha_nacimiento')->widget(
            DatePicker::className(),
            [
                'name' => 'check_issue_date',
                'value' => date('y-m-d', strtotime('+2 days')),
                'options' => ['placeholder' => 'Seleccione la fecha ...'],
                'pluginOptions' => [
                    'format' => 'dd-mm-yyyy',
                    'autoclose' => true,
                    // 'todayHighlight' => true
                ]
            ]
        );
    ?>

    <?= $form->field($model, 'telefono')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'celular')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tipo_paciente')->widget(Select2::classname(), [
            'data' => [
                'TRANSPORTISTA' => 'TRANSPORTISTA',
                'ELFEC' => 'ELFEC',
            ],
            'options' => ['placeholder' => 'Seleccione una opcion ...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]);
    ?>

    <div class="form-group text-right">
        <?php if($tipo && !$id){ ?>
            <?=  Html::a('<i class="material-icons">clear</i> Cerrar', [$tipo.'/create', 'tipo'=>$tipo], ['class' => 'btn btn-default']) ?>
        <?php }elseif($tipo && $id){ ?>
            <?=  Html::a('<i class="material-icons">clear</i> Cerrar', [$tipo.'/update', 'tipo'=>$tipo,'id'=>$id], ['class' => 'btn btn-default']) ?>
        <?php }else{?>
            <?= Html::a("<i class='material-icons'>clear</i> " . 'Cerrar', ['index'], [
                'class' => 'btn btn-default',
                'title' => 'Cerrar',
            ]) ?>
        <?php } ?>
        <?= Html::submitButton("<i  onclick='this.onclick=function(){this.disabled = true};' class='material-icons'>save</i> " . 'Guardar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-warning']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/paciente/kardex.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use kartik\date\DatePicker;
use kartik\form\ActiveForm;
use kartik\select2\Select2;
use yii\widgets\DetailView;
use yii\helpers\ArrayHelper;
use app\models\TipoTratamiento;

/* @var $this yii\web\View */
/* @var $model app\models\Reserva */

$this->title = 'Paciente ' . $paciente->nombrecompleto;
$this->params['breadcrumbs'][] = ['label' => 'Pacientes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="reserva-view">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-centered">
            <div class="card">
                <div class="card-content">
                    <h3 class="text-center reporte">
                        Kardex Paciente
                        <!-- <a class="btn btn-info" href="<?= Url::to(['paciente/kardexpdf', 'id' => $paciente->id]) ?>" target="_blank">
                            <i class="material-icons">print</i> Imprimir
                        </a> -->
                    </h3>
                    <hr>
                    <table class="table">
                        <tbody style="background-color:#A9D0F5">
                            <tr>
                                <td>
                                    <strong> Nombre: </strong> <?= $paciente->nombrecompleto ?>
                                </td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>
                                    <strong> Edad: </strong> <?= $paciente->edad ?> Años
                                </td>
                                <td>
                                    <strong> Fecha Nacimiento: </strong> <?= $paciente->fecha_nacimiento ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <strong> Telefono: </strong> <?= $paciente->telefono ?> - <?= $paciente->celular ?>
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                    <br>
                    <div class="row">
                        <?php $form = ActiveForm::begin([
                            'options'=>[
                                'class' => 'disable-submit-buttons',
                            ] 
                        ]); ?>
                        <div class="table-responsive">
                            <div class="panel panel-primary">
                                <div class="panel-body">
                                    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
                                        <div class="col-lg-4 col-sm-4 col-md-4 col-xs-12">
                                            <div class="form-group">
                                                <?= $form->field($model, 'fecha')->widget(
                                                    DatePicker::className(),
                                                    [
                                                        'name' => 'check_issue_date',
                                                        'value' => date('y-m-d', strtotime('+2 days')),
                                                        'options' => ['placeholder' => 'Seleccione la fecha ...'],
                                                        'pluginOptions' => [
                                                            'format' => 'yyyy-mm-dd',
                                                            'autoclose' => true,
                                                            'todayHighlight' => true
                                                        ]
                                                    ]
                                                );
                                                ?>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-sm-4 col-md-4 col-xs-12">
                                            <div class="form-group">
                                                <?= $form->field($model, 'tipo')->widget(Select2::classname(), [
                                                    'data' => [
                                                        'Consulta' => "Consulta",
                                                        'Reconsulta' => "Reconsulta",
                                                        'Tratamiento' => "Tratamiento",
                                                    ],
                                                    'options' => ['placeholder' => 'Seleccione una opcion ...'],
                                                    'pluginOptions' => [
                                                        'allowClear' => true
                                                    ],
                                                ]);
                                                ?>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-sm-4 col-md-4 col-xs-12">
                                            <div class="form-group">
                                                <?= $form->field($model, 'tratamiento_id')->widget(Select2::classname(), [
                                                    'data' => ArrayHelper::map(TipoTratamiento::find()->where(['>', 'cantidad', '0'])->all(), 'id', 'nombre'),
                                                    'options' => ['placeholder' => 'Seleccione un tratamiento...'],
                                                    'pluginOptions' => [
                                                        'allowClear' => true
                                                    ],
                                                ]);
                                                ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
                                        <div class="col-lg-3 col-sm-3 col-md-3 col-xs-12">
                                            <div class="form-group">
                                                <?= $form->field($model, 'detalle')->textarea(['maxlength' => true, 'rows' => '6']) ?>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-sm-3 col-md-3 col-xs-12">
                                            <div class="form-group">
                                                <?= $form->field($model, 'num_pagina')->textInput(['maxlength' => true]) ?>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-sm-3 col-md-3 col-xs-12">
                                            <div class="form-group">
                                                <?= $form->field($model, 'num_doc')->textInput(['maxlength' => true]) ?>
                                            </div>
                                        </div>
                                        <div class="col-lg-3 col-sm-3 col-md-3 col-xs-12" style="padding-top: 25px;">
                                            <div class="form-group">
                                              <button  onclick='this.onclick=function(){this.disabled = true};' name="agregar" type="submit" class="btn btn-success" id="bt_agregar">
                                                    <i class="material-icons">save</i>Guardar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php ActiveForm::end(); ?>
                    </div>
                    <table class="table table-striped table-bordered table-condensed table-hover">
                        <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Tipo</th>
                                <th>Tipo tratamiento</th>
                                <th>Detalle</th>
                                <th>N° Doc</th>
                                <th>Pagos</th>
                                <th>Num Pagina</th>
                                <th>Estado</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($kardexes as $kardex) { ?>
                                <tr <?= $kardex->getEstados($kardex->estado) ?>>
                                    <td width="7%"><?= $kardex->fecha ?></td>
                                    <td width="7%"><?= $kardex->tipo ?></td>
                                    <td width="8%"><?= $kardex->tratamiento ? $kardex->tratamiento->nombre : '' ?></td>
                                    <td width="30%"><?= $kardex->detalle ?></td>
                                    <td><?= $kardex->num_doc ?></td>
                                    <td><?= $kardex->getPagostoal() ? $kardex->getPagostoal() : $kardex->getPagoscons() ?></td>
                                    <td><?= $kardex->num_pagina ?></td>
                                    <td><?= $kardex->estado ?></td>
                                    <td class="text-center">
                                        <?php if ($kardex->estado == 'Pendiente') { ?>
                                            <?php if (Yii::$app->user->can('Administrador') || Yii::$app->user->can('Secretaria')) { ?>
                                                <a class="btn btn-success btn-round btn-just-icon" href="<?= Url::to(['paciente/estado', 'id' => $kardex->id]) ?>" title="Cambiar estado" aria-label="Cambiar estado" data-confirm="¿ Esta seguro de cambiar de estado este elemento ?" data-method="post">
                                                    <i class="material-icons">remove_circle_outline</i>
                                                </a>
                                            <?php } ?>
                                          
                                        <?php } ?>

                                        <a href="<?= Url::to(['paciente/kardexupdate', 'id' => $kardex->id]) ?>" class="btn btn-warning btn-round btn-just-icon" title="Editar kardex">
                                                <i class="material-icons">edit</i>
                                            </a>

                                        <a class="btn btn-info btn-round btn-just-icon" href="<?= Url::to(['paciente/kardexpdf', 'id' => $kardex->id, 'paciente_id' => $kardex->paciente_id]) ?>" target="_blank">
                                            <i class="material-icons">print</i>
                                        </a>
                                        <?php if($kardex->tipo == 'Tratamiento'){ ?>
                                        <a class="btn btn-danger btn-round btn-just-icon" href="<?= Url::to(['paciente/pagos', 'id' => $kardex->id]) ?>" title="Kardex pagos">
                                            <i class="material-icons">attach_money</i>
                                        </a>
                                        <?php }?>

                                        <?php if($kardex->tipo == 'Consulta'){ ?>
                                            <a class="btn btn-warning btn-round btn-just-icon" href="<?= Url::to(['paciente/pagoconsulta', 'id' => $kardex->id]) ?>" title="Kardex pago consulta">
                                                <i class="material-icons">attach_money</i>
                                            </a>
                                        <?php }?>
                                        <a href="<?= Url::to(['paciente/receta', 'id' => $kardex->id]) ?>" class="btn btn-primary btn-round btn-just-icon" title="Receta medica">
                                            <i class="material-icons">assignment</i>
                                        </a>
                                        <a href="<?= Url::to(['paciente/kardexdelete', 'id' => $kardex->id]) ?>" class="btn btn-danger btn-round btn-just-icon" title="Eliminar">
                                            <i class="material-icons">delete</i>
                                        </a>
                                     
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <div class="form-group text-right">
                        <?= Html::a("<i class='material-icons'>clear</i> " . 'Cerrar', ['index'], ['class' => 'btn btn-default', 'title' => 'Cerrar',]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>